
Name:           perl-RT-Extension-CommandByMail
Version:        0.10
Release:        9%{?dist}
Summary:        Change metadata of a RT ticket via email
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/RT-Extension-CommandByMail/
Source0:        http://www.cpan.org/authors/id/F/FA/FALCONE/RT-Extension-CommandByMail-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(CPAN)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(MIME::Entity) >= 5.420
BuildRequires:  perl(Test::More)
BuildRequires:  perl(UNIVERSAL::require)
BuildRequires:  perl(RT)
BuildRequires:  /usr/sbin/rt-mailgate
Requires:       perl(MIME::Entity) >= 5.420
Requires:       perl(RT::Interface::Email)
Requires:       perl(UNIVERSAL::require)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This extension allows you to manage tickets via RT's email interface. You put
commands into beginning of a mail and extension applies them. See the list
of commands in the RT::Interface::Email::Filter::TakeAction docs.

%prep
%setup -q -n RT-Extension-CommandByMail-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
%{?_with_tests: make test }




%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes README INSTALL
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Sun Aug 04 2013 Fedora Release Engineering <rel-eng@lists.fedoraproject.org> - 0.07-9
- Rebuilt for https://fedoraproject.org/wiki/Fedora_20_Mass_Rebuild

* Thu Feb 14 2013 Fedora Release Engineering <rel-eng@lists.fedoraproject.org> - 0.07-8
- Rebuilt for https://fedoraproject.org/wiki/Fedora_19_Mass_Rebuild

* Fri Jul 20 2012 Fedora Release Engineering <rel-eng@lists.fedoraproject.org> - 0.07-7
- Rebuilt for https://fedoraproject.org/wiki/Fedora_18_Mass_Rebuild

* Wed Jul 04 2012 Petr Pisar <ppisar@redhat.com> - 0.07-6
- Perl 5.16 rebuild

* Fri Jan 13 2012 Fedora Release Engineering <rel-eng@lists.fedoraproject.org> - 0.07-5
- Rebuilt for https://fedoraproject.org/wiki/Fedora_17_Mass_Rebuild

* Tue Jul 19 2011 Petr Sabata <contyk@redhat.com> - 0.07-4
- Perl mass rebuild

* Fri Mar 10 2011 David Nalley <david@gnsa.us> 0.07-3
- change R perl(RT::Interface::Email) 
- fixed spaces v tab issue
* Fri Nov 05 2010 David Nalley <david@gnsa.us> 0.07-2
- change BR perl(RT) rather than rt3
- made test optional
* Thu Nov 04 2010 David Nalley <david@gnsa.us> 0.07-1
- Specfile autogenerated by cpanspec 1.78.
- Commented out test section
- added INSTALL to docs b/c they contain information per
- added R and BR for rt3
