Name:           perl-Plack-Middleware-Test-StashWarnings
Version:        0.08
Release:        0.1%{?dist}
Summary:        Test your application's warnings
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Plack-Middleware-Test-StashWarnings/
Source0:        http://www.cpan.org/modules/by-module/Plack/Plack-Middleware-Test-StashWarnings-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch

BuildRequires:  perl >= 1:5.8.1
BuildRequires:  perl-macros
BuildRequires:  perl(Module::Install)

BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(HTTP::Request::Common)
BuildRequires:  perl(Plack)
BuildRequires:  perl(Plack::Request)
BuildRequires:  perl(Plack::Test)
BuildRequires:  perl(Test::Harness)
BuildRequires:  perl(Test::More)
Requires:       perl(Plack)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Plack::Middleware::Test::StashWarnings is a Plack middleware component to
record warnings generated by your application so that you can test them to
make sure your application complains about the right things.

%prep
%setup -q -n Plack-Middleware-Test-StashWarnings-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Mon Oct 13 2014 "Nico Kadel-Garcia <nkadel@gmail.com>" 0.08-0.1
- Update to version 0.08.

* Wed Nov 27 2013 "Nico Kadel-Garcia <nkadel@gmail.com>" 0.07-1
- Specfile autogenerated by cpanspec 1.78.
- Add perl(Test::More), perl(Test::Harness) to BuildRequires.
