Name:           perl-Test-SharedFork
Version:        0.29
Release:        1%{?dist}
Summary:        Fork test
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Test-SharedFork/
Source0:        http://www.cpan.org/authors/id/E/EX/EXODIST/Test-SharedFork-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 0:5.008_001
BuildRequires:  perl(App::Prove)
BuildRequires:  perl(ExtUtils::MakeMaker) >= 6.64
BuildRequires:  perl(Test::Builder) >= 0.32
BuildRequires:  perl(Test::Builder::Module)
BuildRequires:  perl(Test::Builder::Tester)
BuildRequires:  perl(Test::More) >= 0.88
BuildRequires:  perl(Test::Requires)
BuildRequires:  perl(Time::HiRes)
Requires:       perl(Test::Builder) >= 0.32
Requires:       perl(Test::Builder::Module)
Requires:       perl(Test::More) >= 0.88
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Test::SharedFork is utility module for Test::Builder.

%prep
%setup -q -n Test-SharedFork-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes cpanfile LICENSE META.json minil.toml README.md README.mkdn
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Mon Oct 13 2014 Nico Kadel-Garcia <nkadel@gmail.com> 0.29-1
- Specfile autogenerated by cpanspec 1.78.
