Name:           perl-Locale-Maketext-Fuzzy
Version:        0.11
Release:        0.1%{?dist}
Summary:        Maketext from already interpolated strings
License:        Distributable
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Locale-Maketext-Fuzzy/
Source0:        http://www.cpan.org/modules/by-module/Locale/Locale-Maketext-Fuzzy-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 0:5.005
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Locale::Maketext)
BuildRequires:  perl(Test::More)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This module is a subclass of Locale::Maketext, with additional support for
localizing messages that already contains interpolated variables.

%prep
%setup -q -n Locale-Maketext-Fuzzy-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes README README.mkdn
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Sun Feb 08 2015 Nico Kadel-Garcia <nkadel@gmail.com> 0.11-1
- Specfile autogenerated by cpanspec 1.78.
