Name:           perl-HTML-FormatText-WithLinks
Version:        0.15
Release:        1%{?dist}
Summary:        HTML to text conversion with links as footnotes
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/HTML-FormatText-WithLinks/
Source0:        http://www.cpan.org/authors/id/S/ST/STRUAN/HTML-FormatText-WithLinks-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(HTML::FormatText) >= 2
BuildRequires:  perl(HTML::TreeBuilder)
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(URI::WithBase)
Requires:       perl(HTML::FormatText) >= 2
Requires:       perl(HTML::TreeBuilder)
Requires:       perl(URI::WithBase)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
HTML::FormatText::WithLinks takes HTML and turns it into plain text but
prints all the links in the HTML as footnotes. By default, it attempts to
mimic the format of the lynx text based web browser's --dump option.

%prep
%setup -q -n HTML-FormatText-WithLinks-%{version}

%build
%{__perl} Build.PL installdirs=vendor
./Build

%install
rm -rf $RPM_BUILD_ROOT

./Build install destdir=$RPM_BUILD_ROOT create_packlist=0
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
./Build test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes examples META.json README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Sun Feb 08 2015 Nico Kadel-Garcia <nkadel@gmail.com> 0.15-1
- Specfile autogenerated by cpanspec 1.78.
