Name:           perl-Test-Simple
Version:        1.001006
Release:        0.1%{?dist}
Summary:        Basic utilities for writing tests
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Test-Simple/
Source0:        http://www.cpan.org/authors/id/E/EX/EXODIST/Test-Simple-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 0:5.006
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Test::Harness) >= 2.03
Requires:       perl(Test::Harness) >= 2.03
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

# Classic perl misnumbering zero-fills package nambers, requires backfill
#Provides: perl(Test::Builder) = 1.001006
Provides: perl(Test::Builder) = 1.24
#Provides: perl(Test::Builder::IO::Scalar) = 2.111
#Provides: perl(Test::Builder::Module) = 1.001006
#Provides: perl(Test::Builder::Module) = 1.001006
Provides: perl(Test::Builder::Module) = 1.24
#Provides: perl(Test::Builder::Tester) = 1.24
#Provides: perl(Test::Builder::Tester::Color) = 1.24
Provides: perl(Test::Builder::Tester::Tie)  
#Provides: perl(Test::More) = 1.001006
Provides: perl(Test::More) = 1.24
#Provides: perl(Test::Simple) = 1.001006
Provides: perl(Test::Simple) = 1.24
Provides: perl-Test-Simple = 1.001006-0.1.el6

%description
** If you are unfamiliar with testing read Test::Tutorial first! **

%prep
%setup -q -n Test-Simple-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes META.json README TODO
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Mon Oct 13 2014 Nico Kadel-Garcia <nkadel@gmail.com> 1.001006-1
- Specfile autogenerated by cpanspec 1.78.
