Name:           perl-Test-Simple
Version:        1.001014
Release:        1%{?dist}
Summary:        Basic utilities for writing tests
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Test-Simple/
Source0:        http://www.cpan.org/modules/by-module/Test/Test-Simple-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 0:5.006
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Test::Harness) >= 2.03
Requires:       perl(Test::Harness) >= 2.03
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
** If you are unfamiliar with testing read Test::Tutorial first! **

%prep
%setup -q -n Test-Simple-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes META.json README TODO
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Mon Feb 02 2015 Nico Kadel-Garcia <nkadel@gmail.com> 1.001006-1
- Specfile autogenerated by cpanspec 1.78.
